services:
  app:
    build: .
    container_name: yugen-app
    expose:
      - "8080"
    networks:
      - yugen-network
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./wallet:/app/wallet:ro
    restart: always

  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: yugen-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - yugen-network
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - app
networks:
  yugen-network:
    driver: bridge