spring.application.name=trabajo-final-integrador

# ===== ORACLE AUTONOMOUS =====
spring.datasource.url=jdbc:oracle:thin:@yugendb_low?TNS_ADMIN=C:/oracle/wallets/YUGENDB
spring.datasource.username=YUGEN_APP
spring.datasource.password=Shizukukazumi*8

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===== JPA / HIBERNATE =====
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
