spring.application.name=yugen-store
server.port=8080
server.ssl.enabled=false

# Datasource
spring.datasource.url=jdbc:oracle:thin:@YUGENDB_LOW?TNS_ADMIN=D:/Nico/Proyectos/Ecommerce/yugen-store/wallet
spring.datasource.username=YUGEN_APP
spring.datasource.password=Shizukukazumi*8
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.properties.hibernate.default_schema=YUGEN_APP

# Control de siembra de datos
app.data.seed.enabled=true

# *****************************************************************
salesforce.client-id=3MVG9JJwBBbcN47IaQ.5iHtlBLG4_.Ld_H5HnUcawfWcOkmvjtTWXafLFX1EJlAQQoq8KkfP4a8p2a3P2zL70
salesforce.client-secret=F7B074A947A36A0124918DEFB1CF00183B7196AE05886810EF8EC58959593E2E
salesforce.login-url=https://brave-panda-67fbzi-dev-ed.trailblaze.my.salesforce.com/services/oauth2/token
salesforce.username=carrizonicolasd8@gmail.com
salesforce.password=shizuku08bWYfOFYvCP5ikuPVXGKTxasH